// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaSUBg6zGqNenZSsyrkvWXKL6RjXmXOA0',
    appId: '1:1054933483047:web:93122062c615bd6bb51802',
    messagingSenderId: '1054933483047',
    projectId: 'sapienpantry',
    authDomain: 'sapienpantry.firebaseapp.com',
    databaseURL: 'https://sapienpantry-default-rtdb.firebaseio.com',
    storageBucket: 'sapienpantry.appspot.com',
    measurementId: 'G-Q8KSL5SNYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHlOQCoK1rIWVtN_SZeuuka33OTWXVz1M',
    appId: '1:1054933483047:android:37a45bf706c7efdcb51802',
    messagingSenderId: '1054933483047',
    projectId: 'sapienpantry',
    databaseURL: 'https://sapienpantry-default-rtdb.firebaseio.com',
    storageBucket: 'sapienpantry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7pcfM8yH-O0IpCW_WvkOrUPwRS17MO-4',
    appId: '1:1054933483047:ios:af3aa9d69e26a9c4b51802',
    messagingSenderId: '1054933483047',
    projectId: 'sapienpantry',
    databaseURL: 'https://sapienpantry-default-rtdb.firebaseio.com',
    storageBucket: 'sapienpantry.appspot.com',
    androidClientId: '1054933483047-38ravenaa1pcbc9gibos4veeheoslh8m.apps.googleusercontent.com',
    iosClientId: '1054933483047-un5p8nhthfkhptd9do14rboep11id34l.apps.googleusercontent.com',
    iosBundleId: 'com.cixhub.sapienpantry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7pcfM8yH-O0IpCW_WvkOrUPwRS17MO-4',
    appId: '1:1054933483047:ios:af3aa9d69e26a9c4b51802',
    messagingSenderId: '1054933483047',
    projectId: 'sapienpantry',
    databaseURL: 'https://sapienpantry-default-rtdb.firebaseio.com',
    storageBucket: 'sapienpantry.appspot.com',
    androidClientId: '1054933483047-38ravenaa1pcbc9gibos4veeheoslh8m.apps.googleusercontent.com',
    iosClientId: '1054933483047-un5p8nhthfkhptd9do14rboep11id34l.apps.googleusercontent.com',
    iosBundleId: 'com.cixhub.sapienpantry',
  );
}
